projects:
  User Badges App:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: android
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-2
        apiId: q5h7yrf275h63ksiyituxtusce
        maxDepth: 4
extensions:
  amplify:
    version: 3
